CREATE USER 'student'@localhost IDENTIFIED BY 'xstudentx';
CREATE USER 'teacher'@localhost IDENTIFIED BY 'xteacherx';
CREATE USER 'admin'@localhost IDENTIFIED BY 'xadminx';
CREATE USER 'counselor'@localhost IDENTIFIED BY 'xcounselorx';
 
-- user privileges
 
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'teacher'@'localhost', 'counselor'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT ON *.* TO 'student'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;